/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./*.php', './backend/admin/**/*.php', './assets/js/**/*.js'],
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#002200',
        'on-primary-container': '#009904',
        'primary-fixed': '#77ff62',
        'on-primary-fixed': '#002200',
        'primary-fixed-dim': '#00cc00',
        'on-primary-fixed-variant': '#006e02',
        surface: '#f9f9ff',
        'on-surface': '#111c2c',
        'on-surface-variant': '#45464d',
        'surface-tint': '#006e02',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-dim': '#d8daea',
        outline: '#75777e',
        'outline-variant': '#c5c6ce',
        tertiary: '#006e46',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#009962',
        'on-tertiary-container': '#002113',
        'tertiary-fixed': '#95f6c6',
        'on-tertiary-fixed': '#002113',
        'tertiary-fixed-dim': '#79d9ab',
        'on-tertiary-fixed-variant': '#005232',
      },
      fontFamily: {
        headline: ['"DM Sans"', 'sans-serif'],
        body: ['"Inter"', 'sans-serif'],
        label: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        sm: '8px',
        DEFAULT: '16px',
        lg: '24px',
        xl: '32px',
        pill: '9999px',
      },
      spacing: {
        'gutter': '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'stack-xl': '64px',
        'unit': '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'container-max': '1280px',
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.15', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.25', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '1.35', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.02em' }],
        'label-md': ['12px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.02em' }],
        'label-sm': ['10px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.04em' }],
        'stat-lg': ['48px', { lineHeight: '1', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
